export const nonConsumableConfig = [
  { name: "ledgerNo", label: "Ledger No", type: "text" },
  { name: "poRefNoDate", label: "PO Ref No/Date", type: "text" },
  { name: "receivedFrom", label: "Received From", type: "text" },
  { name: "itemDescription", label: "Item Description", type: "text" },
  { name: "groundBalance", label: "Ground Balance", type: "number" },
  { name: "ledgerBalance", label: "Ledger Balance", type: "number" },
  { name: "qtyUnit", label: "Quantity Unit", type: "text" },
  { name: "fundingHead", label: "Funding Head", type: "text" },
  { name: "projectCode", label: "Project Code", type: "text" },
  { name: "amountInclGST", label: "Amount (Incl. GST)", type: "number" },
  { name: "location", label: "Location", type: "text" },
  { name: "qty", label: "Quantity", type: "number" },
  { name: "rate", label: "Rate", type: "number" },
  { name: "value", label: "Value", type: "number" },
  {
    name: "capitalizedFinancialYear",
    label: "Capitalized Financial Year",
    type: "text",
  },
  {
    name: "remarksStockAuthority",
    label: "Remarks (Stock Authority)",
    type: "text",
  },
  { name: "remarksHODHOC", label: "Remarks (HOD/HOC)", type: "text" },
  { name: "caOrder", label: "CA Order", type: "text" },
  { name: "assetCode", label: "Asset Code", type: "text" },
  { name: "finalSupplyDate", label: "Final Supply Date", type: "date" },
  { name: "assetHead", label: "Asset Head", type: "text" },
  { name: "billInvoiceNoDate", label: "Bill/Invoice No/Date", type: "text" },
]
